spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/acmclub?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    database:
      db1: 0
      db2: 1
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0 #支持文件写入磁盘
      resolve-lazily: false  #是否支持 multipart 上传文件时懒加载
#     TODO 设置文件存储位置
      location: /src/main/resources/static/
  mail:
    host: smtp.gmail.com
    username: swang0652@gmail.com
    password: kktuyhocrjhlndcv
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        debug: false
        smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          ssl:
            enable: true
    expiration: 1800

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/*.xml

server:
  port: 8082

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"

officialWebsite:
  jwt:
    secret: kktuyhocrjhlndcv
    expiration: 86400

