spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.16.42:3306/acm-web-site?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: BNEUQACMhenrik
    # Hikari 连接池配置
    hikari:
      minimum-idle: 3  # 最小空闲连接数量
      maximum-pool-size: 5  # 连接池最大连接数，默认是10
      max-lifetime: 30000 # 此属性控制池中连接的最长生命周期
      connection-test-query: SELECT 1

  redis:
    host: 101.43.16.42
    port: 6379
    password: B&NEUQ#ACM@henrik
    username: default
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0 #支持文件写入磁盘
      resolve-lazily: false  #是否支持 multipart 上传文件时懒加载
      #     TODO 设置文件存储位置
      location: /usr/local/file/

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/*.xml

server:
  port: 8082

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"

officialWebsite:
  jwt:
    secret: kktuyhocrjhlndcv
    expiration: 86400

